# Generated by Django 4.1.2 on 2022-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='software',
            name='screenshots1',
            field=models.ImageField(default='', upload_to='scre'),
        ),
        migrations.AddField(
            model_name='software',
            name='screenshots2',
            field=models.ImageField(default='', upload_to='scre'),
        ),
        migrations.AddField(
            model_name='software',
            name='screenshots3',
            field=models.ImageField(default='', upload_to='scre'),
        ),
        migrations.AddField(
            model_name='software',
            name='screenshots4',
            field=models.ImageField(default='', upload_to='scre'),
        ),
        migrations.AddField(
            model_name='software',
            name='screenshots5',
            field=models.ImageField(default='', upload_to='scre'),
        ),
        migrations.AddField(
            model_name='software',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='reldate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
