# Generated by Django 4.1.2 on 2022-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_software_screenshots_software_screenshots1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='term',
            field=models.CharField(default='', max_length=180),
        ),
    ]
