# Generated by Django 4.1.2 on 2022-11-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_software_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='average',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='software',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
    ]
