# Generated by Django 4.1.2 on 2022-11-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_software_average_software_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='update',
            field=models.CharField(default='', max_length=50),
        ),
    ]
