# Generated by Django 4.1.2 on 2022-11-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_software_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='update',
            field=models.BooleanField(blank=True, default=False, max_length=50),
        ),
    ]
