# Generated by Django 4.1.2 on 2022-11-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_software_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='instapos',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
